<?php
/**
 * @var string $class
 * @var string $message
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CAPTCHA demo</title>
    <style>
        .success{color: green}
        .warning{color: goldenrod}
        .error{color: red}
    </style>
</head>
<body>
<h1>CAPTCHA Demo</h1>
<hr>
<h3><a href="index.php">Form</a> | Validate</h3>
<hr>
<h2 class="<?= $class ?>"><?= $message ?></h2>
</body>
</html>
