name: Tests
on: [ push, pull_request ]

jobs:
  tests:
    strategy:
      matrix:
        php-versions: [ '8.0', '8.1' ]

    runs-on: ubuntu-latest

    name: Test on PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: PhpUnit test
        if: matrix.php-versions != '8.0'
        run: composer test
        continue-on-error: true

      - name: PhpUnit test-coverage
        if: matrix.php-versions == '8.0'
        working-directory: ./
        run: |
          composer test-coverage
          sed -i 's/\/home\/runner\/work\/captcha\/captcha\//\/github\/workspace\//g' report.xml
          sed -i 's/\/home\/runner\/work\/captcha\/captcha\//\/github\/workspace\//g' clover.xml

      - name: Upload coverage report
        if: matrix.php-versions == '8.0'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mobicms
            -Dsonar.projectName=captcha
            -Dsonar.projectKey=mobicms_captcha
            -Dsonar.sources=./src
            -Dsonar.tests=./tests
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.php.tests.reportPath=report.xml
            -Dsonar.php.coverage.reportPaths=clover.xml
