name: Tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        php-versions: ['7.4','8.0']

    runs-on: ubuntu-latest

    name: Test on PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: PhpUnit test
        if: matrix.php-versions == '8.0'
        run: composer test
        continue-on-error: true

      - name: PhpUnit test-coverage
        if: matrix.php-versions == '7.4'
        run: |
          composer test-coverage
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover clover.xml
